#pragma once


#ifndef ENABLE_VISUALIZER
#ifdef PLATFORM_WINDOWS
#define ENABLE_VISUALIZER 1
#endif
#endif


#define USE_STABLE_SORT 1
#define NEW_TWO_POINT 0
#define USE_ROTATION_PREDICTION 1
#define USE_NAIVE_ML_DATAASSOCIATION 1

#define DISABLE_ACC_BIAS 0

#define USE_SQ_NOISE 0

#define USE_GIVENS_UPDATE 1

#define USE_STATIC_DETECTION 1

#define STATIC_OBSERVER 1
#define USE_GIVENS_MARGIN 1

#define USE_NEW_ZUPT 1

#define USE_KEYFRAME 1

#define USE_STATIC_STACK 1

#define REMOVE_RESIDUAL_STACK 1

#define USE_DEPTH_PRIOR 0

#define USE_PLANE_PRIOR 0

#define USE_HARRIS 0

#define TEST_VISION_MODULE 0

#define USE_NEW_STATIC_DETECT 1

#define USE_NEW_MOVED_PIXEL 0

#define USE_VELOCITY_DETECT_ROTATION 0

#define USE_POSITION_DETECT_ROTATION 0


#define USE_Z_AXIS 1