%YAML:1.0
---
# System parameters
SerialRun: 1
RecordImage: 0
RecordImu: 0
NoGUI: 0
NoDebugOutput : 1
DataFps : 60
RunVIO: 1
ResultOutputPath: ""
ResultOutputName: ""
ResultOutputFormat: "TUM" # TUM/KITTI/EUROC

# Sensor calibration path
DataSourceConfigFilePath: ""
CameraCalibrationPath: ""


#FeatureTracker Parameters
MaxNumToTrack: 350
MaskSize: 41 #Must be Odd