%YAML:1.0
---
# System parameters
SerialRun: 1
RecordImage: 0
RecordImu: 0
NoGUI: 0
NoDebugOutput : 1
MaxRunFPS: 20
RunVIO: 1
ResultOutputPath: ""
ResultOutputName: ""
ResultOutputFormat: "TUM" # TUM/KITTI/EUROC
# sensor switch
UseGnss: 1
UseStereo: 1

# Sensor calibration path
DataSourceConfigFilePath: ""
CalibrationPath: ""


#FeatureTracker Parameters
MaxNumToTrack: 350
MaskSize: 41 #Must be Odd
UseBackTracking: 1