%YAML:1.0
---

DataSourceType: "ROS2" # support: ROS2/Euroc/ROS2_bag
DataSourcePath: "" # used for non-ROS2 data source
ImageStartIdx: 10 # skip the first n images in the dataset

ROSTopics:
    - 
      TopicName: "/t265/fisheye1/image_raw"
      TopicQueueSize: 10
      SensorID: 0 # Index of each sensor
      SensorType: "StereoCamera"
      RightTopicName: "/t265/fisheye2/image_raw"
    - 
      TopicName: "/t265/accel/sample"
      TopicQueueSize: 10
      SensorID: 0
      SensorType: "ACC"
    - 
      TopicName: "/t265/gyro/sample"
      TopicQueueSize: 10
      SensorID: 0
      SensorType: "GYRO"
