%YAML:1.0

SensorType: IMU
SensorId: 0

# IMU parameters
GyroNoise: 2e-4  # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
AccNoise: 2e-3   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
GyroBiasNoise: 2e-5 # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
AccBiasNoise: 3e-3 # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
ImuSampleFps: 62
AccSampleFps: 62
GyroSampleFps: 200

# IMU to Body
Tbs: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.000467073, -0.00841767, 0.999964, 0.237693,
         0.999777, -0.0211047, 0.000289326, -0.0494227,
         0.0211015, 0.999742, 0.00842565, 0.894904,
         0.0, 0.0, 0.0, 1.0]
